name: Operator Unit Tests

on:
  pull_request:
    paths-ignore:
      - 'internal/**'
      - 'cmd/**'

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "No relevant changes detected to run tests."